name: Publish
on:
    release:
        types: [created]

jobs:
    publish-gpr:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Setup Repo
              uses: actions/checkout@v4
            - name: Setup PNPM
              uses: pnpm/action-setup@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: "https://registry.npmjs.org"
                  cache: "pnpm"
            - name: Install Dependencies
              run: pnpm install --frozen-lockfile
            - name: Lint and Build
              run: pnpm run lint && pnpm run build
            - name: Publish
              run: pnpm publish --no-git-checks
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
